# SecretStore: Cấu hình kết nối tới provider bên ngoài
# Lab 2.1: Dùng "fake" provider để giả lập AWS Secrets Manager trên minikube
# → Không cần AWS credentials thật, chứng minh đúng pattern ESO
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: fake-store
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    fake:
      data:
        - key: demo/db/password
          value: "initial-secret-value-from-store"
          version: "v1"
